[package]
name = "obfustr-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
getrandom = "0.2.15"
proc-macro2 = "1.0.89"
quote = { version = "1.0.37" }
syn = { version = "2.0.85", default-features = false }
